pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/YOUR_USERNAME/YOUR_REPO.git'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "CI pipeline running"'
            }
        }
    }
}